### PR TITLE
publicsuffix: update table to latest list from publicsuffix.org on 2016-05-26

### PR DESCRIPTION
**Pull request by yookoala**
Update to the publicsuffix/list@b13ac4c

Allowing quite a large amount of public suffix domains (like noip.com) users to overcome the [rate limit problem](https://github.com/certbot/certbot/issues/1607) (certbot/certbot#1607).

### CODE REVIEW

**Comment by yookoala** [comment]
According to @bradfitz in [golang/net#15518](https://github.com/golang/go/issues/15518#issuecomment-217312171), they have no intention to keep re-generating their publicsuffix frequently. That means if letsencrypt is using the exact version of publicsuffix in [golang/net](https://github.com/golang/net), it will almost never be updated.

That creates the necessity to update the publicsuffix locally.

**Comment by ccppuu** [comment]
Hi @yookoala, thanks for the PR.

In the near future we will be removing this `golang/net` fork entirely and migrating to using @weppos' [publixsuffix-go package](https://github.com/weppos/publicsuffix-go). This should help address the upstream Golang net package's PSL generation schedule and give us more flexibility moving forward. We will have the opportunity to update the PSL boulder uses at that point.

**Comment by yookoala** [comment]
@ccppuu  I created this PR for a very practical and urgent purpose. I uses quite a lot of noip.com based domain. And these domain are not supported by letsencrypt because of the rate limit issue, which depends on publicsuffix update. I really want to use SSL encryption for my sites.

Is there any roadmap for the `publixsuffix-go` patch for the [boulder](https://github.com/letsencrypt/boulder) package? What can I do to speed this up?

**Comment by kaefert** [comment]
A lot of no-ip users have waited for half a year for the chance to get to use letsencrypt to secure their servers that don't have bought domains.

@ccppuu Would it be a lot of effort to merge and deploy this PR into the letsencrypt production environment? If not, would you consider doing this additional work for a quick relief for us long waiting wanna-be letsencrypt users?

Else, could you give us a timeline / roadmap of the alternative as @yookoala asked? Please forgive my ignorance, I only have a very rough understanding of the letsencrypt system.

**Comment by jsha** [comment]
@kaefert @yookoala: Give us a couple more weeks. If we can't land the "nice" solution by then, we'll talk about fetching the latest PSL directly into this fork.

Thanks,
Jacob

**Comment by kaefert** [comment]
thanks jsha for the response and for the roadmap :)

**Pull request closed without merging**
