### PR TITLE
publicsuffix: update table to latest list from publicsuffix.org on 2016-01-30

### PR DESCRIPTION
**Pull request by ricardopadilha**
This PR includes all commits from upstream up to and including golang/net@6c581b9.

(Hopefully this time the commit history is in order.)

### CODE REVIEW

**Comment by bradfitz** [comment]
@jmhodges, FWIW, I double checked the public suffix update in that list (6c581b96a7d38dd755f986fcf4f29665597694c0) when it went into upstream, that it passed all the tests from upstream and wasn't tampered with.

**Comment by jmhodges** [comment]
LGTM

Thanks, y'all!

**Comment by kaefert** [comment]
dear letsencrypt developers - I would like to request that you merge the newest version of the public suffix list into your project again, now that finally the pull request for the no-ip domains that a lot of your (potential?) users where waiting for since december got merged upstream: https://github.com/publicsuffix/list/pull/64

Thank you very much for your awesome project :)

ps.: if this is not the right place for such a request, please tell me so and also whether a right place for such a request exists and if it does where that might be. thank you.

**Comment by yookoala** [comment]
@kaefert: I have opened #12 for the purpose. Hope letsencrypt developers will merge it.

**Pull request merged**
