### PR TITLE
publicsuffix: update table to latest list from publicsuffix.org on 2016-01-30

### PR DESCRIPTION
**Pull request by ricardopadilha**
This PR includes all commits from upstream up to and including golang/net@6c581b9.

### CODE REVIEW

**Comment by jmhodges** [comment]
There is an additional commit in this branch that is not in golang's master: https://github.com/ricardopadilha/net/commit/653efee7ae4b22037b4b4eb94939acbec6d0e9c0

We won't be accepting this PR with it in place.

**Comment by jmhodges** [comment]
To be clear, while this likely was an accident, and just an innocuous merge commit, we don't have the bandwidth to review all of the code from our 3rd party dependencies. Knowing our third party code came from only the people we expected to is a good way to limit security risk, and maintaining a clean git history relative to the upstream repo makes it easy for us to update to the upstream's latest in the future.

**Comment by ricardopadilha** [comment]
Sorry, my mistake. I did a git pull instead of a git merge. I'll submit another PR.

**Comment by ricardopadilha** [comment]
Post mortem: it seems the VM I use for Linux development got a clock drift of 11607 seconds over night, which inverted the order of the commits. Resubmitted as #8.

**Pull request closed without merging**
